### ISSUE TITLE
Замечания по работе №3

### ISSUE THREAD

**Issue by AndriiLitvin** [vshap/vshap.github.io#2]
Визуально:
http://joxi.ru/gmvgpyqt63p02a
1) Верхняя менюшка прыгает
2) текст в верхнем меню не четкий
3)Левое меню поправь бордеры
4) Блок не отцентрирован http://joxi.ru/1A5pK7zFq3oX2E
5) текст в менюшке смещается только тогда когда наведешь на надпись, сделай чтоб при наведении на блок менялось.

Код:
1)Шрифты подключаются в начале

**Comment by vshap** [comment]
1) Верхняя менюшка прыгает - пофиксил
2) текст в верхнем меню не четкий - убрал  тень
3)Левое меню поправь бордеры - схлопнул
4) Блок не отцентрирован - не понял. у меня во всех браузерах по центру
5) текст в менюшке смещается только тогда когда наведешь на надпись, сделай чтоб при наведении на блок менялось - меняется

Код:
1)Шрифты подключаются в начале - перенес

**Comment by AndriiLitvin** [comment]
4) Блок не отцентрирован - не понял. у меня во всех браузерах по центру
в .main не правильно задан маргин потому так выходит. зажми "ctrl"+скрол роликом мыши и увидишь.
1) в header_menu бекграунд куртинкой зделай через цвет(градиент)
2)Левая менюшка при ховер делает смещение не в право а в лево.
3)Левое меню поправь бордеры - схлопнул
ну маргин это конечно выход, но просто на разных браузерах такое решение будет вести себя по разному. обнули бордер боттом и последнему елементу задай его через псевдокласс

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
