### ISSUE TITLE
Замечания по работе №4

### ISSUE THREAD

**Issue by AndriiLitvin** [vshap/vshap.github.io#3]
1) треугольник сделай через css http://htmlbook.ru/blog/treugolniki-cherez-css
тегу "а" задаешь позыционирование релейтив
а треугольник пихаешь в а:before и ровняешь так ка тебе надо.  либо через спецсимволы http://htmlweb.ru/html/symbols.php
просто выглядит не очень http://joxi.ru/8AnVER6uYVd4AO
2) Ховер на подменю интерстный но не кайфово когда за менюшкой видно текст, убери прозрачность

**Comment by vshap** [comment]
1) Треугольник сделал через спецсимвол
2) Прозрачность убрал

**Comment by AndriiLitvin** [comment]
1)text-shadow не надо. - убрал.
Про те страшные паддинги - http://xiper.net/collect/html-and-css-tricks/karkas-verstki/kolonki-ravnoy-visoty - ссылку давал Олег. Мне тоже решение не особо, но работает

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
