### ISSUE TITLE
Замечания по работе 5.1 cadastre

### ISSUE THREAD

**Issue by AndriiLitvin** [vshap/vshap.github.io#4]
http://joxi.ru/823pdlkFEGyxAO
1)сделать на всю ширину браузера - исправил
2)Бекграунд не совсем такой, присмотрись к макету там не такая структура - исправил
3)кнопку сверстать, картинка не катит
4)сверстать ане картинкой
5)при фокусе такой же эфект как и при ховере - исправил

**Comment by AndriiLitvin** [comment]
http://joxi.ru/Y2L0zPXs3XYp26
1)отцентрировать
2) при ресайзе окна меню улетает вправо

сделать правки предыдущие и пиши отдельный комментарий а не правь мой, а то оно меня дезориентирует

**Comment by vshap** [comment]
1. Верхнее меню прижато вправо, да (как на макете). 
2. http://joxi.ru/LmGeQaPCyEXgAl - так это вижу я. (20" 1600х900). Как поправить, если я не смогу увидеть результат...

**Comment by AndriiLitvin** [comment]
> Верхнее меню прижато вправо, да (как на макете).

там нужно сделать контейнер 1215рх шириной отцентрировать его и туда пихнуть контент хедера. просто на широких экранах оно вообще не понятно где будет а форма по центру и то  она не совсем по центру .

> http://joxi.ru/LmGeQaPCyEXgAl - так это вижу я. (20" 1600х900). Как поправить, если я не смогу увидеть результат...

зажимаешь Ctrl+ролик на мышке крутишь и все увидишь
http://ruseller.com/lessons.php?id=1248
https://learn.javascript.ru/css-center 
http://plnkr.co/edit/qtx9kz5JyNKr5CPKRL7i?p=preview

**Comment by vshap** [comment]
Меню отцентрировал
Форму отцентрировал
Facebook сваял

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
